# Composition
from tabulate import tabulate

class ReportBuilder:
    """
    Builds a Markdown report from narrative text, quality scores, and EDA results.

    This class takes the output of the pipeline (narrative insights, data quality scores, 
    and EDA results) and formats them into a Markdown string suitable for reporting 
    or presentation purposes.

    Attributes:
        _narrative (list): List of narrative strings describing insights.
        _scores (dict): Dictionary of data quality scores (missing, duplicates, outliers, balance, overall).
        _eda (dict): Dictionary containing EDA results (summary statistics, missing values, outliers, etc.).
    """

    def __init__(self, narrative, scores, eda_results):
        """
        Initialize ReportBuilder.

        Args:
            narrative (list): Narrative text generated by the Narrator class.
            scores (dict): Data quality scores generated by QualityScorer.
            eda_results (dict): EDA results generated by NumericAnalyzer and CategoricalAnalyzer.
        """
        self._narrative = narrative
        self._scores = scores
        self._eda = eda_results

    def to_markdown(self):
        """
        Convert the narratives, scores, and EDA results into a Markdown formatted report.

        Returns:
            str: Markdown string containing the report with sections:
                - Narrative Insights
                - Quality Scores (tabulated)
        """
        md = ["# Automated EDA Report\n", "## Narrative Insights"]
        for s in self._narrative:
            md.append(f"- {s}")
        md.append("\n## Quality Scores")
        rows = [(k, v) for k, v in self._scores.items()]
        md.append(tabulate(rows, headers=["Metric", "Score"], tablefmt="github"))
        return "\n\n".join(md)
